### ISSUE TITLE
Add html5 push state middleware

### ISSUE THREAD

**Issue by thoop** [skoczen/django-seo-js#16]
It looks like the hashbang middleware checks for _escaped_fragment_ but the html5 push state section of the escaped fragment protocol says that URLs like:

`http://www.example.com/user/1` with the `<meta name="fragment" content="!">` meta tag will be accessed like:

`http://www.example.com/user/1?_escaped_fragment_=`

The current hashbang middleware might catch that case just fine but I had someone ask a question where it wasn't working because they took the hashbang middleware hour since they used html5 push state.

If the hashbang middleware would work for this case, then maybe that middleware should just be changed to escapedfragment or something instead of hashbang.

Thanks!

**Comment by skoczen** [comment]
+1 to this. Renaming to `EscapedFragmentMiddleware`, and deprecating `HashBangMiddleware`, with scheduled removal on v0.5.

**Comment by skoczen** [comment]
This is now released in `0.3.1.`  Thanks for the contributions!

**Comment by thoop** [comment]
Thanks!

**Comment by skoczen** [comment]
Absolutely - thanks again for the issues and input.  It's fantastic to have someone who's working on SEO stuff (on our default backend, even) every day keeping an eye out, and raising flags. It makes it so much easier for this project to keep up with an ever-shifting landscape.

Much appreciated.
