### ISSUE TITLE
Remove Googlebot from user agent check to prevent cloaking penalty

### ISSUE THREAD

**Issue by thoop** [skoczen/django-seo-js#17]
https://github.com/skoczen/django-seo-js/blob/master/django_seo_js/settings.py#L49

Googlebot, Yahoo, bingbot should be removed from that list as soon as possible to prevent anyone from being penalized for cloaking. Those three crawlers support the escaped fragment protocol so that you do not have to match them by user agent. If you do match them by user agent, they could think you are cloaking and penalize your website in the search results.

**Comment by skoczen** [comment]
Great, thanks for this and your other issue, Todd.  Will get both of these out and release on my next open-source project sprint (hopeful it's this week.)

**Comment by thoop** [comment]
No problem at all. Thanks so much!

**Comment by skoczen** [comment]
Fixed, going out shortly!

**Comment by thoop** [comment]
Thanks @skoczen!
