### ISSUE TITLE
Supported versions of Python and Django missing from docs

### ISSUE THREAD

**Issue by Alex3917** [skoczen/django-seo-js#19]

**Comment by skoczen** [comment]
Mostly because I didn't to a full test when building it. :)  Is there a particular version you're seeing problems on?

**Comment by Alex3917** [comment]
I actually hadn't installed it because I wasn't even sure if it was for Python 2 or 3 (or both).

**Comment by skoczen** [comment]
I'm sure it runs in 2.7, pretty sure about 2.6, and less confident on 2.5 and lower.  It should run in 3, but my projects were still in 2.7 when I wrote it, so there may be minor porting issues.

Generally, the code from 2.7 to 3 is pretty compatible.   I'd say if this meets a need you have, give it a shot, and if you run into trouble, report an issue here!  

Thanks!
