### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by mikeyaa** [skoczen/django-seo-js#24]
I'm getting the following error, python v 3.4:

from base import SEOBackendBase, RequestsBasedBackend
ImportError: No module named 'base'

Is this due to lack of Python 3 support? A bit confused at this error.

**Comment by pjdelport** [comment]
See PR #26.

**Comment by mkaliberda** [comment]
@mikeyaa, add dot to import
site-packages/django_seo_js/backends/prerender.py
site-packages/django_seo_js/backends/test.py
like this
from .base import SEOBackendBase, RequestsBasedBackend
from .base import SEOBackendBase

**Comment by pcraciunoiu** [comment]
This should be fixed now, with 0.3.2. Closing, but please confirm if you see issues!
