### ISSUE TITLE
Why is the requests dependency pinned?

### ISSUE THREAD

**Issue by PiDelport** [skoczen/django-seo-js#27]
Currently, this library pins requests to `requests==2.2.1`.

Is there a reason for this? If not, this should be loosened to just `requests`: it's not a good idea for a library to pin versions that might conflict with downstream projects' requirements.

**Comment by pjdelport** [comment]
Note that PR #26 un-pins this, and it seems to work okay.

**Comment by derek-adair** [comment]
Hey just a heads up @skoczen is pretty busy at the moment and isn't very active on github any longer.  I'm sure he'd be interested in receiving some help maintaining this project as it seems you have your head wrapped around it already.

Feel free to reach out to him via email (listed in his [profile](https://github.com/skoczen))

**Comment by pjdelport** [comment]
I don't quite have the bandwidth to take on maintenance of this project right now either, unfortunately. :/
